[project]
name = "project-tahsheek-el-gambary"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Adham Gaweesh", email = "adhamgaweesh@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pillow>=12.3.0",
]

[project.scripts]
project-tahsheek-el-gambary = "project_tahsheek_el_gambary:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
