; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = atmelavr
board = ATmega32
framework = arduino

; ---- SubTask 1 ----
[env:subtask1]
build_src_filter = +<subtask1/>

; ---- SubTask 2 ----
[env:subtask2]
build_src_filter = +<subtask2/>

; ---- SubTask 3 ----
[env:subtask3]
build_src_filter = +<subtask3/>
